import "./globals.css"

import type { Metadata } from "next"
import { Badge, Flex, Theme, ThemePanel } from "@radix-ui/themes"

import { inter } from "@/lib/fonts"
import { SiteHeader } from "@/components/site-header"
import { TailwindIndicator } from "@/components/tailwind-indicator"
import { ThemeProvider } from "@/components/theme-provider"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Theme
            accentColor="mint"
            grayColor="gray"
            panelBackground="solid"
            scaling="100%"
            radius="medium"
          >
            <Flex direction="column">
              <SiteHeader />
              {children}
            </Flex>
            <ThemePanel />
            <TailwindIndicator />
          </Theme>
        </ThemeProvider>
      </body>
    </html>
  )
}
